<a href="https://colab.research.google.com/github/LeonimerMelo/GANs/blob/main/Upsampling_Example_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import UpSampling2D, Input

In [ ]:
# input data
X = np.asarray([[1, 2], [3, 4]])
# X = np.random.rand(2, 2)
print('X array:\n', X)
print('\nX shape:', X.shape)

X array:
 [[1 2]
 [3 4]]

X shape: (2, 2)


In [ ]:
# reshape input data for Sequential model
X = X.reshape((1, 2, 2, 1))
print(X)
print(X.shape)

[[[[1]
   [2]]

  [[3]
   [4]]]]
(1, 2, 2, 1)


In [ ]:
# define model
model = Sequential()
model.add(Input((2, 2, 1)))
model.add(UpSampling2D(size=(3, 3)))
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ up_sampling2d_4 (UpSampling2D)       │ (None, 6, 6, 1)             │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# model output
output = model.predict(X)
print(output.shape)
output_ = output.reshape((6, 6))
print(output_.shape)
print(output_)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
(1, 6, 6, 1)
(6, 6)
[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]]
